### ISSUE TITLE
训练时频繁出现与内存有关的报错

### ISSUE THREAD

**Issue by notastudio** [kerlomz/captcha_trainer#3]
Windows 10, Python 3.6.7 64-bit, CUDA 9.0, tensorflow-gpu 1.11, CNN 分支(因为 LSTM 对于我的训练数据而言似乎效果不好)
内存 8GB, 显存 6GB.
训练数据集是 5 万张 240x60 大小的 JPG 图片.

一般是执行 `python .\trains.py` 一段时间后就报错退出.报错信息有这三种情况.
1
```
Traceback (most recent call last):
  File ".\trains.py", line 185, in <module>
    train_process()
  File ".\trains.py", line 79, in train_process
    batch_x, batch_y = get_next_batch(64, False)  # 64
  File ".\trains.py", line 115, in get_next_batch
    batch_x = np.zeros([batch_size, IMAGE_HEIGHT * IMAGE_WIDTH])
MemoryError
```
2
几屏幕的 CUDA 和 tensorflow 的报错信息,大概说的是内存分配失败 (原文是 Memory, 指的是内存还是显存?), 就像这样:
```
2018-11-04 01:54:01.061494: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 2.00G (2147483648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```
3
没有报错信息,执行到这里之后就直接退出了:
```
Session Initializing...
Loading history archive...
Initialized.
---------------------------------------------------------------------------------
```

但是我在任务管理器中看到,在报错退出之前,内存和显存的占用率都没有占满.这是怎么回事?应该怎么修复呢?

**Comment by notastudio** [comment]
在 `config.yaml` 中设置 `DeviceUsage: 0.3` 后解决了,但性能有所下降.
其实挺玄学的,之前训练一个规模相同的数据集时用的是 `DeviceUsage: 0.9`, 并没有报错,不知道这一次是怎么回事.

**Comment by kerlomz** [comment]
不好意思太忙了没注意看，240*50的图片有点大，可能你的显卡吃不消，我觉得可以试试（1）调小批次大小，（2）或者对图片做resize预处理，比如改成200*50稍微进行一点缩放，最后（3）设备使用率提高，但是不能太高，太高可能会影响正常使用。

**Comment by notastudio** [comment]
谢谢大佬解答.想问问"调小批次大小"是怎样操作的呢?是在 `config.yaml` 中设置吗?
